# -*- coding: utf-8 -*-
"""Audio_Exercise_Train_Test_Splitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gC-wvZXw4f56yQy3X5yW4PA6mKaZyUeU
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Load the CSV file

- Please uploadn the given csv file to the colab environment.
"""

import pandas as pd

CSV_PATH = "/content/drive/MyDrive/AIClub_AP_Nandigam_Subash/Datasets/music_instrument_feature.csv"

# read the csv
data = pd.read_csv(CSV_PATH)
data.head()

"""### Check the labels and labels count"""

# label count
data["LABEL"].value_counts()

"""### Split the data into train and test

- We use the scikit-learn (another python module) to split the dataset.
- It takes 2 parameters mainly.
    - array - Data to split
    - test_size  - Test size as percentage
    - random_state - To have a constant randomness (Otherwise every time you run different data will be there in df_train and df_test)
"""

from sklearn.model_selection import train_test_split

# split the dataset
df_train, df_test = train_test_split(data, test_size = 0.2, random_state = 0)

# reset the indexes
df_train.reset_index(drop = True, inplace = True)
df_test.reset_index(drop = True, inplace = True)

print("Train Data", df_train.shape)
print("Test data", df_test.shape)

"""### Now save the CSVs
- Please make sure to download the CSVs from colab environment
"""

# save the train csv
df_train.to_csv("/content/drive/MyDrive/AIClub_AP_Nandigam_Subash/Datasets/music_instrument_feature_train.csv", index = False)
# save the test csv
df_test.to_csv("/content/drive/MyDrive/AIClub_AP_Nandigam_Subash/Datasets/music_instrument_feature_test.csv", index = False)